### ISSUE TITLE
Space.charts() throws exception if child Stream has color attribute set

### ISSUE THREAD

**Issue by HaydenSikh** [librato/python-librato#119]
I'm setting up a script to create and update our spaces.  In order to update existing charts rather than deleting them and creating them fresh, I pull the existing charts using the `Space.charts()` method.  This worked until one of the charts had colors manually assigned to its Streams at which point I instead get an exception.

This occurred with version 1.0.2.

Sample REPL session to recreate:
```
>>> user = ...
>>> token = ...
>>> api = librato.connect(user, token)
>>> space = api.get_space(...)
>>> space.charts()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/haydensikh/workspace/librato-spaces/.env/lib/python2.7/site-packages/librato/spaces.py", line 36, in charts
    self._charts = self.connection.list_charts_in_space(self)
  File "/Users/haydensikh/workspace/librato-spaces/.env/lib/python2.7/site-packages/librato/__init__.py", line 486, in list_charts_in_space
    charts = self._parse({"charts": resp}, "charts", Chart)
  File "/Users/haydensikh/workspace/librato-spaces/.env/lib/python2.7/site-packages/librato/__init__.py", line 201, in _parse
    return [cls.from_dict(self, m) for m in resp[name]]
  File "/Users/haydensikh/workspace/librato-spaces/.env/lib/python2.7/site-packages/librato/spaces.py", line 169, in from_dict
    related_space=data.get('related_space'))
  File "/Users/haydensikh/workspace/librato-spaces/.env/lib/python2.7/site-packages/librato/spaces.py", line 146, in __init__
    self.streams.append(Stream(**i))
TypeError: __init__() got an unexpected keyword argument 'color'
```

**Comment by josephruscio** [comment]
Thanks for reporting this! Some of the devs who spearhead this project are out on vacation this week but we'll get it in the queue cc @jderrett @drio

**Comment by drio** [comment]
@HaydenSikh I have released a new version that should fix the issue you were experiencing. Please give it a try and let us know.

**Comment by HaydenSikh** [comment]
Worked like a charm.  Thank you.
